name: CI

on:
  push:
    branches: [main, moiz1]
  pull_request:
    branches: [main, moiz1]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports: ['27017:27017']
        options: --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Install Backend dependencies
        working-directory: ./Backend
        run: npm ci

      - name: Lint Backend
        working-directory: ./Backend
        run: npx eslint .

      - name: Type Check Backend
        working-directory: ./Backend
        run: npx tsc --noEmit

      # Add backend tests here if you have them
      # - name: Test Backend
      #   working-directory: ./Backend
      #   run: npm test

      # Frontend
      - name: Install Frontend dependencies
        working-directory: ./Frontend
        run: npm ci

      - name: Lint Frontend
        working-directory: ./Frontend
        run: npx eslint .

      - name: Type Check Frontend
        working-directory: ./Frontend
        run: npx tsc --noEmit

      - name: Build Frontend
        working-directory: ./Frontend
        run: npm run build
